### ISSUE TITLE
C++ Support?

### ISSUE THREAD

**Issue by flbulgarelli** [mgarciaisaia/mumuki-cspec-server#1]
Does this runner have support for C++?

**Comment by mgarciaisaia** [comment]
I think it doesn't, but maybe it's just a little tweak.

`gcc` has the odd custom of depending on the file's extension to determine which language to compile. [We are hardcoding `.c`](https://github.com/mgarciaisaia/mumuki-cspec-server/blob/broken/lib/test_compiler.rb#L6).

I don't know if there's anything else needed than changing that to `.cpp` - never done any C++ in my life.

May mumuki need to send the language to the server's anyway?

**Comment by mgarciaisaia** [comment]
Repo has been archived
